select * from customers

--Q1. What is the total revenue generated by male vs, female customers?

select gender, sum(purchase_amount) as revenue
from customers 
group by gender

--Q2. which customers used discount but still spent more than the average purchase amount?
select customer_id, purchase_amount 
from customers 
where discount_applied = 'yes' and purchase_amount >= (select AVG(purchase_amount)from customers)


--Q3. Which are the top 5 products with the highest average review rating?

select top 5 item_purchased, round(avg(review_rating),2) as [Average Product Rating]
from customers
group by item_purchased 
order by avg(review_rating) desc


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

select shipping_type, AVG(purchase_amount) 
from customers
where shipping_type in ('Standard','Express')
group by shipping_type

--Q5. Do subscribed customers spend more? compare average spend and total revenue between subscribers and non-subscribers.

select subscription_status,count(customer_id) as [Total Customers], AVG(purchase_amount) as [average spent], sum(purchase_amount) as [total revenue]
from customers
group by subscription_status

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select top 5 item_purchased,
sum(case when discount_applied = 'yes' then 1 else 0 end)*100/count(*) as [Discount_rate]
from customers
group by item_purchased
order by Discount_rate desc


--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment:
with customer_type as (
select customer_id, previous_purchases,
case 
	when previous_purchases = 1 then 'New'
	When previous_purchases between 2 and 10 then ' Returning'
	else 'Loyal'
	end as [Customer_segment]
from customers)

select Customer_segment, count(*) as [Number of Customers]
from customer_type
group by Customer_segment
order by [Number of Customers]


--Q8. What are the top 3 most purchased products within each category?

with item_counts as (
select category, item_purchased,
count(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) desc) as Item_rank
from customers
group by category, item_purchased

)

select Item_rank, category, total_orders
from item_counts
where Item_rank <= 3;

--Q9. Are customers who are repeated buyers (more_than 5 previous purchases) also likely to subseribe?

select subscription_status, count(customer_id) as repeated_buyers
from customers
where previous_purchases > 5
group by subscription_status


--Q10. What is the revenue contribution of each_ age group?

select age_group, sum(purchase_amount) as Total_Revenue
from customers
group by age_group
order by Total_Revenue desc